<?xml version="1.0"?>
<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
 
 <xacro:property name="PI" value="3.14"/>
 <xacro:property name="minus" value="-1"/>


<!-- body property -->
 <xacro:property name="body_len" value="0.55"/>
 <xacro:property name="body_width" value="0.36"/>
 <xacro:property name="body_height" value="0.10"/>
 <xacro:property name="body_mass" value="10.8"/>

<!-- wheel property -->
 <xacro:property name="wheel_radius" value="0.068"/>
 <xacro:property name="wheel_width" value="0.04"/>
 <xacro:property name="wheel_height" value="0.136"/>
 <xacro:property name="wheel_mass" value="0.2"/>

<!-- track property -->
 <xacro:property name="track_len" value="0.45"/>
 <xacro:property name="track_width" value="0.04"/>
 <xacro:property name="track_height" value="0.136"/>
 <xacro:property name="track_mass" value="0.2"/>

<!-- black box property -->
 <xacro:property name="box_len" value="0.2"/>
 <xacro:property name="box_width" value="0.17"/>
 <xacro:property name="box_height" value="0.064"/>
 <xacro:property name="box_mass" value="0.168"/>

<!-- track wheel property -->
 <xacro:property name="track_wheel_radius" value="0.0045"/>
 <xacro:property name="track_wheel_width" value="0.04"/>
 <xacro:property name="track_wheel_height" value="0.009"/>
 <xacro:property name="track_wheel_mass" value="0.0185"/> 

<!-- wheel1 property -->
 <xacro:property name="wheel1_width" value="0.035"/>
 <xacro:property name="wheel1_mass" value="0.15"/> 

<!-- track1 property -->
 <xacro:property name="track1_len" value="0.39"/>
 <xacro:property name="track1_width" value="0.035"/>
 <xacro:property name="track1_height" value="0.061"/>
 <xacro:property name="track1_mass" value="0.1"/>

<!-- wheel2 property -->
 <xacro:property name="wheel2_radius" value="0.031"/>
 <xacro:property name="wheel2_mass" value="0.05"/>
 <xacro:property name="wheel2_diam" value="0.062"/>


<!-- wheel's inertia-->
 <xacro:macro name="cylinder_inertia" params ="m r h">
  <inertial>
   <mass value="${m}"/>
   <inertia ixx="${m*(3*r*r+h*h)/12}"  ixy="0.0" ixz="0.0"
            iyy="${m*r*r/2}"  iyz= "0.0"
            izz="${m*(3*r*r+h*h)/12}"/>
   </inertial>
 </xacro:macro>

<!-- box inertia -->

 <xacro:macro name="box_inertia" params ="m a b c">
  <inertial>
   <mass value="${m}"/>
   <inertia ixx="${m*(a*a+b*b)/12}"  ixy="0.0" ixz="0.0"
            iyy="${m*(b*b+c*c)/12}"  iyz= "0.0"
            izz="${m*(b*b+c*c)/12}"/>
   </inertial>
</xacro:macro> 

 <xacro:macro name= "inertial_matrix" params="mass">
  <inertial>
    <mass value="${mass}"/>
      <inertia ixx="1.0" ixy="0.0"
               iyy="1.0" iyz="0.0"
               izz="1.0" ixz="0.0"/>
   </inertial>
 </xacro:macro> 


  <link name="base_link">
    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

 <link name="body">
	<collision>
		<geometry>
			<box size="${body_len} ${body_width} ${body_height}"/>
		</geometry>
	</collision>
	<visual>
		<geometry>
			<box size="${body_len} ${body_width} ${body_height}"/>
		</geometry>
	</visual>
	<xacro:box_inertia m="${body_mass}" a="${body_width}" b="${body_height}" c="${body_len}"/>
 </link>

 <joint name="body_joint" type="fixed">
	<parent link="base_link"/>
	<child link="body"/>
	<origin xyz="0 0 0" rpy="0 0 0"/>
 </joint>

 <link name= "box">
	<visual>
		<origin rpy= "0 0 0" xyz= "-0.1 0 0"/>
		<geometry>
			<box size="${box_len} ${box_width} ${box_height}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy= "0 0 0" xyz= "-0.1 0 0"/>
		<geometry>
			<box size="${box_len} ${box_width} ${box_height}"/>
		</geometry>
	</collision>
	<xacro:box_inertia m="${box_mass}" a="${box_width}" b="${box_height}" c="${box_len}"/>
 </link>

 <joint name="box_joint" type="fixed">
	<parent link="body"/>
	<child link="box"/>
	<origin xyz="-0.045 0.02 0.082" rpy="0 0 0"/>
 </joint>

<xacro:macro name="track_wheel" params= "name_link x y z roll">
 <link name= "${name_link}">
	<visual>
		<origin rpy= "${roll} 0 0" xyz= "0 0 0"/>
		<geometry>
			<cylinder length="${track_wheel_width}" radius= "${track_wheel_radius}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy= "${roll} 0 0" xyz= "0 0 0"/>
		<geometry>
			<cylinder length="${track_wheel_width}" radius= "${track_wheel_radius}"/>
		</geometry>
	</collision>
  	<inertial>
    		<mass value="${track_wheel_mass}"/>
      		<inertia ixx="0.0002" ixy="0.0"
               		 iyy="0.0002" iyz="0.0"
               		 izz="0.0002" ixz="0.0"/>
   		</inertial>
 </link>

 <joint name="${name_link}_joint" type="continuous">
	<parent link="body"/>
	<child link="${name_link}"/>
	<origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
	<axis xyz="0 1 0"/>
 </joint>

 <gazebo reference ="${name_link}">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0"/>
    <kd value= "1.0"/>
 </gazebo>

 <transmission name="${name_link}_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<actuator name="${name_link}_motor">
		<mechanicalReduction>1</mechanicalReduction>
	</actuator>
	<joint name="${name_link}_joint">
		<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
	</joint>
 </transmission>
</xacro:macro>

<xacro:macro name="wheel" params= "prefix suffix X Y Z">
 <link name= "${prefix}_${suffix}_wheel">
	<visual>
		<origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
		<geometry>
			<cylinder length="${wheel_width}" radius= "${wheel_radius}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
		<geometry>
			<cylinder length="${wheel_width}" radius= "${wheel_radius}"/>
		</geometry>
	</collision>
	<xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
 </link>

 <joint name="${prefix}_${suffix}_wheel_joint" type="fixed">
	<parent link="body"/>
	<child link="${prefix}_${suffix}_wheel"/>
	<origin xyz="${0.225*X} ${(body_width/2 + wheel_width/2)*Y} ${0.02*Z}" rpy="0 0 0"/>
	<axis xyz="0 1 0"/>
 </joint>

 <gazebo reference ="${prefix}_${suffix}_wheel">
    <selfCollide>false</selfCollide>
 </gazebo>
</xacro:macro>


<xacro:macro name="track" params= "prefix Y">
 <link name= "${prefix}_track">
	<visual>
		<origin rpy= "0 0 0" xyz= "0 ${(track_width/2)*Y} 0"/>
		<geometry>
			<box size="${track_len} ${track_width} ${track_height}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy= "0 0 0" xyz= "0 ${(track_width/2)*Y} 0"/>
		<geometry>
			<box size="${track_len} ${track_width} ${track_height}"/>
		</geometry>
	</collision>
	<xacro:box_inertia m="${track_mass}" a="${track_width}" b="${track_height}" c="${track_len}"/>
 </link>

 <joint name="${prefix}_track_joint" type="fixed">
	<parent link="body"/>
	<child link="${prefix}_track"/>
	<origin xyz="0 ${(body_width/2)*Y} -0.02" rpy="0 0 0"/>
 </joint>

 <gazebo reference ="${prefix}_track">
    <selfCollide>false</selfCollide>
 </gazebo>
</xacro:macro>

<xacro:macro name="wheel1" params= "prefix Y">
 <link name= "${prefix}_wheel1">
	<visual>
		<origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
		<geometry>
			<cylinder length="${wheel1_width}" radius= "${wheel_radius}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
		<geometry>
			<cylinder length="${wheel1_width}" radius= "${wheel_radius}"/>
		</geometry>
	</collision>
	<xacro:cylinder_inertia m="${wheel1_mass}" r="${wheel_radius}" h="${wheel1_width}"/>
 </link>

 <joint name="${prefix}_wheel1_joint" type="continuous">
	<parent link="body"/>
	<child link="${prefix}_wheel1"/>
	<origin xyz="0.225 ${((body_width/2) + wheel_width + (wheel1_width/2))*Y} -0.02" rpy="0 0 0"/>
	<axis xyz="0 1 0"/>
	<limit effort="30" velocity="1.0"/>
	<dynamics damping="0.0" friction="0.0"/>
 </joint>

 <transmission name="${prefix}_wheel1_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<actuator name="${prefix}_wheel1_motor">
		<mechanicalReduction>1</mechanicalReduction>
	</actuator>
	<joint name="${prefix}_wheel1_joint">
		<hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
	</joint>
 </transmission>
<gazebo reference ="${prefix}_wheel1">
    <self_collide>false</self_collide>
</gazebo>
</xacro:macro> 

<xacro:macro name="track1" params= "prefix Z">
 <link name= "${prefix}_track1">
	<visual>
		<origin rpy= "0 0 0" xyz= "${track1_len/2} 0 ${((wheel_height-track1_height)/2)*Z}"/>
		<geometry>
			<box size="${track1_len} ${track1_width} ${track1_height}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy= "0 0 0" xyz= "${track1_len/2} 0 ${((wheel_height-track1_height)/2)*Z}"/>
		<geometry>
			<box size="${track1_len} ${track1_width} ${track1_height}"/>
		</geometry>
	</collision>
	<xacro:box_inertia m="${track1_mass}" a="${track1_width}" b="${track1_height}" c="${track1_len}"/>
 </link>

 <joint name="${prefix}_track1_joint" type="fixed">
	<parent link="${prefix}_wheel1"/>
	<child link="${prefix}_track1"/>
	<origin xyz="0 0 0" rpy="0 0 0"/>
	<dynamics damping="0.0" friction="0.0"/>
 </joint>

<gazebo reference ="${prefix}_track1">
    <self_collide>false</self_collide>
</gazebo>
</xacro:macro>

<xacro:macro name="wheel2" params= "prefix Z">
 <link name= "${prefix}_wheel2">
	<visual>
		<origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
		<geometry>
			<cylinder length="${track1_width}" radius= "${wheel2_radius}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy= "${PI/2} 0 0" xyz= "0 0 0"/>
		<geometry>
			<cylinder length="${track1_width}" radius= "${wheel2_radius}"/>
		</geometry>
	</collision>
	<xacro:cylinder_inertia m="${wheel2_mass}" r="${wheel2_radius}" h="${track1_width}"/>
 </link>

 <joint name="${prefix}_wheel2_joint" type="fixed">
	<parent link="${prefix}_track1"/>
	<child link="${prefix}_wheel2"/>
	<origin xyz="${track1_len} 0 ${((wheel_height-track1_height-0.001)/2)*Z}" rpy="0 0 0"/>
	<axis xyz="0 1 0"/>
	<dynamics damping="0.0" friction="0.0"/>
 </joint>

<gazebo reference ="${prefix}_wheel2">
    <self_collide>false</self_collide>
</gazebo>
</xacro:macro>

<xacro:macro name="track2" params= "prefix">
 <link name= "${prefix}_track2">
	<visual>
		<origin rpy= "0 0 0" xyz= "${track1_len/2} 0 ${wheel_radius-(wheel2_diam/2)}"/>
		<geometry>
			<box size="${track1_len} ${track1_width} ${wheel2_diam}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy= "0 0 0" xyz= "${track1_len/2} 0 ${wheel_radius-(wheel2_diam/2)}"/>
		<geometry>
			<box size="${track1_len} ${track1_width} ${wheel2_diam}"/>
		</geometry>
	</collision>
	<xacro:box_inertia m="${track1_mass}" a="${track1_width}" b="${track1_height}" c="${track1_len}"/>
 </link>

 <joint name="${prefix}_track2_joint" type="fixed">
	<parent link="${prefix}_wheel1"/>
	<child link="${prefix}_track2"/>
	<origin xyz="0 0 0" rpy="0 ${PI/16.6} 0"/>
	<dynamics damping="0.0" friction="0.0"/>
 </joint>
<gazebo reference ="${prefix}_track2">
    <self_collide>false</self_collide>
</gazebo>
</xacro:macro>

<xacro:macro name="aux_track_wheel" params= "aux_name_link prefix x z roll">
 <link name= "${aux_name_link}">
	<visual>
		<origin rpy= "${roll} 0 0" xyz= "0 0 0"/>
		<geometry>
			<cylinder length="${wheel1_width}" radius= "${track_wheel_radius}"/>
		</geometry>
	</visual>
	<collision>
		<origin rpy= "${roll} 0 0" xyz= "0 0 0"/>
		<geometry>
			<cylinder length="${wheel1_width}" radius= "${track_wheel_radius}"/>
		</geometry>
	</collision>
  	<inertial>
    		<mass value="${track_wheel_mass}"/>
      		<inertia ixx="0.0002" ixy="0.0"
               		 iyy="0.0002" iyz="0.0"
               		 izz="0.0002" ixz="0.0"/>
   		</inertial>
 </link>

 <joint name="${aux_name_link}_joint" type="continuous">
	<parent link="${prefix}_wheel1"/>
	<child link="${aux_name_link}"/>
	<origin xyz="${x} 0 ${z}" rpy="0 0 0"/>
	<axis xyz="0 1 0"/>
 </joint>

 <gazebo reference ="${aux_name_link}">
    <mu1 value="200.0"/>
    <mu2 value="100.0"/>
    <kp value="10000000.0"/>
    <kd value= "1.0"/>
 </gazebo>

 <transmission name="${aux_name_link}_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<actuator name="${aux_name_link}_motor">
		<mechanicalReduction>1</mechanicalReduction>
	</actuator>
	<joint name="${aux_name_link}_joint">
		<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
	</joint>
 </transmission>
</xacro:macro>



<xacro:wheel prefix="right" suffix="back" X="-1" Y="-1" Z="-1"/>
<xacro:wheel prefix="left" suffix="back" X="-1" Y="1" Z="-1"/>
<xacro:wheel prefix="right" suffix="front" X="1" Y="-1" Z="-1"/>
<xacro:wheel prefix="left" suffix="front" X="1" Y="1" Z="-1"/>
<xacro:track prefix="right" Y="-1"/>
<xacro:track prefix="left" Y="1"/> 
<xacro:wheel1 prefix="right" Y="-1"/>
<xacro:wheel1 prefix="left" Y="1"/>
<xacro:track1 prefix="right" Z="-1"/>
<xacro:track1 prefix="left" Z="-1"/>
<xacro:wheel2 prefix="right" Z="-1"/>
<xacro:wheel2 prefix="left" Z="-1"/>
<xacro:track2 prefix="right"/>
<xacro:track2 prefix="left"/>


 <gazebo>
 	<plugin name="gazebo_ros_control" filename= "libgazebo_ros_control.so">
   		<robotNamespace>/</robotNamespace>
  	</plugin>
 </gazebo>

	<xacro:include filename="$(find second_robot)/world/tracks.xacro"/>
	<xacro:include filename="$(find second_robot)/world/aux_tracks.xacro"/>

</robot>
